sudo: false
language: node_js
node_js:
  - "12.18.1"
script:
  - npm i
  - npm run-script build
  - cp ./dist/index.html ./dist/404.html # This allows slash-routing
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: dist
  on:
    branch: master